/* SUNGRID — campaign maps (12) + arena for Wave/Endless.
   Loader-style module: "use strict", global consts, no import/export.
   Loaded by <script> AFTER js/data.js (data.js reads window.MAPS when present). */
"use strict";

/* Map legend:
   "." ground (buildable)      "#" rock (blocks movement AND building)
   "M" mineral deposit         "W" rich deposit
   "S" enemy spawn (walkable for enemies, not buildable)
   "K" base core — exactly one per map.
   All maps are 20 rows x 20 columns. Validate with: node tools/validate.js */

const MAPS = {
  /* ============================== CAMPAIGN ============================== */
  campaign: [
    {
      /* L1 — tutorial: network + power plants. One spawn, short direct lane,
         generous open space around the core. */
      name: "First Grid", waves: 3, coreHp: 100,
      tutorial: [
        "Build two Power Plants next to the Core.",
        "Connect the Core and plants with Links — sun atoms will flow through the grid.",
        "Energy is speed: build, reload and repair faster when supplied.",
        "Crawlers are already coming from the west. Hold the Core!",
      ],
      enemies: ["crawler"],
      map: [
        "....................",
        "....................",
        ".......##...........",
        "....................",
        "....................",
        "....................",
        "..........MM........",
        "....................",
        "....................",
        "S.........K.........",
        "....................",
        "....................",
        "..........MM........",
        "....................",
        "....................",
        ".......##...........",
        "....................",
        "....................",
        "....................",
        "....................",
      ],
    },
    {
      /* L2 — tutorial: harvesters + credits. One spawn, four mineral clusters,
         two of them close to the core. */
      name: "Crystals and Credits", waves: 3, coreHp: 100,
      tutorial: [
        "Place Harvesters on mineral deposits — they dig credits.",
        "Harvesters eat energy too: keep the grid strong.",
        "Credits buy buildings. Energy sets the pace.",
      ],
      enemies: ["crawler", "swarm"],
      map: [
        "....................",
        "....................",
        "....................",
        ".........S..........",
        "....................",
        "....MM..............",
        "....MM..............",
        "....................",
        "..............MM....",
        "..........K...MM....",
        "....................",
        "....MM..............",
        "....MM..............",
        "....................",
        "..............MM....",
        "..............MM....",
        "....................",
        "....................",
        "....................",
        "....................",
      ],
    },
    {
      /* L3 — tutorial: first laser-link. One spawn, rock wall with a narrow
         3-tile throat in front of the core — perfect for a linked laser. */
      name: "The Throat", waves: 3, coreHp: 100,
      tutorial: [
        "Time for your first laser link!",
        "Build 2-3 Lasers at the throat, then: click a Laser → LINK → another Laser.",
        "The receiver gains damage and range. Laser chains win the fight.",
      ],
      enemies: ["crawler", "swarm", "tank"],
      map: [
        "..........##........",
        "..........##........",
        "..........##........",
        "..........##........",
        "..........##........",
        "..........##...MM...",
        "..........##...MM...",
        "..........##........",
        "....................",
        "S..............K....",
        "....................",
        "..........##........",
        "..........##.MM.....",
        "..........##.MM.....",
        "..........##........",
        "..........##........",
        "..........##........",
        "..........##........",
        "..........##........",
        "..........##........",
      ],
    },
    {
      /* L4 — standard: the long way round. Three full-width rock walls with
         alternating gaps turn the map into a serpentine: bottom -> right gap,
         middle -> left gap, upper band -> right gap, core in the top band. */
      name: "The Long Way", waves: 4, coreHp: 110,
      tutorial: [],
      enemies: ["crawler", "swarm", "tank", "kamikaze"],
      map: [
        "....................",
        "....MM..............",
        "....MM..K...........",
        "....................",
        "#################...",
        "....................",
        "....................",
        "..............MM....",
        "..............MM....",
        "...#################",
        "....................",
        "............MM......",
        "............MM......",
        "....................",
        "#################...",
        "....................",
        "....................",
        "S...W...............",
        "....W...............",
        "....................",
      ],
    },
    {
      /* L5 — standard: two fronts. Mirror spawns north and south, rocks on the
         flanks, rich deposits on the east/west lanes. */
      name: "Two Fronts", waves: 5, coreHp: 110,
      tutorial: [],
      enemies: ["crawler", "swarm", "tank", "kamikaze"],
      map: [
        ".........S..........",
        "....................",
        "....................",
        "...##..........##...",
        "...##..........##...",
        "....................",
        "........MM..........",
        "....................",
        "....................",
        "....W....K.....W....",
        "....................",
        "....................",
        "........MM..........",
        "....................",
        "...##..........##...",
        "...##..........##...",
        "....................",
        "....................",
        ".........S..........",
        "....................",
      ],
    },
    {
      /* L6 — standard: island rocks. Scattered rock islands in open ground,
         two diagonal spawns. */
      name: "Islands", waves: 5, coreHp: 110,
      tutorial: [],
      enemies: ["crawler", "swarm", "tank", "teleporter"],
      map: [
        "....................",
        "....S...............",
        "....................",
        "......###...........",
        "......###...........",
        "....................",
        ".........MM.........",
        "..............##....",
        "..........K...##....",
        "..............##....",
        "...MM...............",
        "....###.............",
        "....###.............",
        "....................",
        "..............###...",
        "..............###...",
        "....................",
        "...............S....",
        "....................",
        "....................",
      ],
    },
    {
      /* L7 — standard: rich open field. Almost no rocks, four W deposits,
         two diagonal spawns — a race to claim the rich ground. */
      name: "Rich Field", waves: 5, coreHp: 120,
      tutorial: [],
      enemies: ["crawler", "swarm", "tank", "kamikaze", "rocket"],
      map: [
        "....................",
        "..S.................",
        "....................",
        "....................",
        "......W.......W.....",
        "....................",
        "....................",
        "....................",
        ".........K..........",
        "....................",
        "....................",
        "....................",
        "......W.......W.....",
        "....................",
        "....................",
        "....................",
        "...............##...",
        "...............S....",
        "....................",
        "....................",
      ],
    },
    {
      /* L8 — standard: the spiral. Double rock rings; the only way in is the
         long ring corridor into the sealed inner chamber. */
      name: "The Spiral", waves: 5, coreHp: 120,
      tutorial: [],
      enemies: ["crawler", "swarm", "tank", "kamikaze", "teleporter", "rocket"],
      map: [
        "....................",
        "....................",
        "....................",
        "...################.",
        "...#............#...",
        "...#............#...",
        "...#..########..#...",
        "...#..#......#..#...",
        "...#..#M.....#..#...",
        "S.....#..K......#...",
        "......#.........#...",
        "...#..#....M.#..#...",
        "...#..#......#..#...",
        "...#..########..#...",
        "...#............#...",
        "...#............#...",
        "...################.",
        "....................",
        "....................",
        "....................",
      ],
    },
    {
      /* L9 — hard: the vice. Tight rock pillars, two spawns, one close M and
         rich W tucked into the far corners. */
      name: "The Vice", waves: 6, coreHp: 130,
      tutorial: [],
      enemies: ["crawler", "swarm", "tank", "kamikaze", "sapper", "rocket"],
      map: [
        "....................",
        "................WW..",
        "..S.............WW..",
        ".......##....##.....",
        ".......##....##.....",
        "....................",
        "........M...........",
        "..##.....K......##..",
        "..##............##..",
        "....................",
        "....................",
        "..##............##..",
        "..##............##..",
        "....................",
        ".......##....##.....",
        ".......##....##.....",
        ".................S..",
        "................WW..",
        "....................",
        "....................",
      ],
    },
    {
      /* L10 — hard: three gates. North, west and south spawns; the core sits
         upper-center with a rich field on its east flank. */
      name: "Three Gates", waves: 6, coreHp: 130,
      tutorial: [],
      enemies: ["crawler", "swarm", "tank", "teleporter", "sapper", "rocket"],
      map: [
        "..........S.........",
        "....................",
        "....##.........##...",
        "....##.........##...",
        "....................",
        "..............WW....",
        ".........K.....WW...",
        "....................",
        "..........M.........",
        "S.##....M...........",
        "..##................",
        "....................",
        "..............##....",
        "..............##....",
        "....................",
        "....................",
        "..........S.........",
        "....................",
        "....................",
        "....................",
      ],
    },
    {
      /* L11 — hard: the cage. Core squeezed into the upper-left by pillars,
         three spawns, W deep in the middle of the field. */
      name: "The Cage", waves: 6, coreHp: 140,
      tutorial: [],
      enemies: ["crawler", "swarm", "tank", "kamikaze", "teleporter", "sapper", "rocket"],
      map: [
        "....................",
        "............##..S...",
        ".......##...........",
        ".......##....##.....",
        "....M....##....##...",
        "....M....K..........",
        "....M...............",
        ".......##...........",
        ".......##....##.....",
        "....................",
        ".............WW.....",
        "....................",
        "....##..........##..",
        "....##..........##..",
        "....................",
        "..............##....",
        "....##........##....",
        "....##........##.S..",
        "....................",
        "...S................",
      ],
    },
    {
      /* L12 — final: heart of the swarm. One wide spawn gate (8 tiles) at the
         south edge, a pillar arena in front of the core. Boss wave. */
      name: "Heart of the Swarm", waves: 3, coreHp: 150,
      tutorial: [],
      enemies: ["crawler", "swarm", "tank", "kamikaze", "teleporter", "sapper", "rocket", "boss"],
      map: [
        "....................",
        "....................",
        "......M....K....M...",
        "....................",
        "....................",
        "...#............#...",
        "...#............#...",
        "....................",
        ".........##.........",
        ".........##.........",
        "....................",
        "...#............#...",
        "...#............#...",
        "....................",
        ".........WW.........",
        "....................",
        "....................",
        "....................",
        "....SSSSSSSS........",
        "....................",
      ],
    },
  ],

  /* =============================== ARENA =============================== */
  /* Symetric battlefield for Wave (10 timed waves) and Endless. Four spawn
     gates on the four sides, deposit ring around an open middle. */
  arena: {
    name: "Arena", waves: 10, coreHp: 150,
    tutorial: [],
    enemies: ["crawler", "swarm", "tank", "kamikaze", "teleporter", "sapper", "rocket", "boss"],
    map: [
      "..........S.........",
      "....................",
      "....................",
      "....M............M..",
      "....................",
      "......W.......W.....",
      "....................",
      "....................",
      "....................",
      "S...W.....K.....W..S",
      "....................",
      "....................",
      "....................",
      "......W.......W.....",
      "....................",
      "....M............M..",
      "....................",
      "....................",
      "..........S.........",
      "....................",
    ],
  },
};
